services:
  auth-service:
    build: ./src/auth
    ports:
      - "5001:5001"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - ADMIN_JWT_SECRET=admin_auth_ms_jwt_secret
      - ADMIN_TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - AUTH_SERVICE_PORT=5001
      - DB_NAME=auth_db
    depends_on:
      - auth-db
    networks:
      - microservices-network

  auth-db:
    image: postgres:latest
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"  # Expose different ports for local access
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  orders-service:
    build: ./src/orders
    ports:
      - "5002:5002"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - ADMIN_JWT_SECRET=admin_auth_ms_jwt_secret
      - ADMIN_TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - DB_HOST=orders-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - ORDERS_SERVICE_PORT=5002
      - DB_NAME=order_db
    depends_on:
      - orders-db
    networks:
      - microservices-network

  orders-db:
    image: postgres:latest
    container_name: orders-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5434:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  products-service:
    build: ./src/products
    ports:
      - "5003:5003"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - ADMIN_JWT_SECRET=admin_auth_ms_jwt_secret
      - ADMIN_TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - DB_HOST=products-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PRODUCTS_SERVICE_PORT=5003
      - DB_NAME=product_db
    depends_on:
      - products-db
    networks:
      - microservices-network

  products-db:
    image: postgres:latest
    container_name: products-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    ports:
      - "5435:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  tenant-service:
    build: ./src/tenant
    ports:
      - "5004:5004"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - ADMIN_JWT_SECRET=admin_auth_ms_jwt_secret
      - ADMIN_TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - DB_HOST=tenant-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - TENANT_SERVICE_PORT=5004
      - DB_NAME=tenant_db
    depends_on:
      - tenant-db
    networks:
      - microservices-network

  tenant-db:
    image: postgres:latest
    container_name: tenant-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tenant_db
    ports:
      - "5436:5432"
    volumes:
      - tenant_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  wishlist-service:
    build: ./src/wishlist
    ports:
      - "5005:5005"
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - JWT_SECRET=auth_ms_jwt_secret
      - ADMIN_JWT_SECRET=admin_auth_ms_jwt_secret
      - ADMIN_TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - DB_HOST=wishlist-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - WISHLIST_SERVICE_PORT=5005
      - DB_NAME=wishlist_db
    depends_on:
      - wishlist-db
    networks:
      - microservices-network

  wishlist-db:
    image: postgres:latest
    container_name: wishlist-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wishlist_db
    ports:
      - "5437:5432"
    volumes:
      - wishlist_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

volumes:
  auth_db_data:
  order_db_data:
  product_db_data:
  tenant_db_data:
  wishlist_db_data:

networks:
  microservices-network:
    driver: bridge