apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-db-deployment
  labels:
    app: wishlist-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist-db
  template:
    metadata:
      labels:
        app: wishlist-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: wishlist-db-config
