apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-deployment
  labels:
    app: wishlist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
        - name: wishlist
          image: wishlist-microservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: wishlist-config
