apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: NodePort
  selector:
    app: authentication
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
