apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: products-microservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: products-config
