apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-deployment
  labels:
    app: tenant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      containers:
        - name: tenant
          image: tenant-microservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: tenant-config
